{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "API TFLPIII HORUS BIBLIOTECA",
    "description": "Documentação da API TFLPIII HORUS BIBLIOTECA"
  },
  "host": "localhost:3000",
  "basePath": "/",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/usuario": {
      "get": {
        "tags": [
          "Usuario"
        ],
        "summary": "Consulta lista de usuarios.",
        "description": "Descrição do metodo",
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/aluno": {
      "get": {
        "tags": [
          "Aluno"
        ],
        "summary": "Consulta lista de alunos.",
        "description": "Descrição do metodo",
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "post": {
        "tags": [
          "Aluno"
        ],
        "description": "",
        "parameters": [
          {
            "name": "json",
            "description": "Dados para inserir um novo aluno",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "matricula": {
                  "type": "string",
                  "example": "12345678"
                },
                "dataNascimento": {
                  "type": "string",
                  "example": "2002-07-02"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Criado"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/aluno/{idaluno}": {
      "delete": {
        "tags": [
          "Aluno"
        ],
        "description": "",
        "parameters": [
          {
            "name": "idaluno",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Nenhum Conteúdo"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "aluno/{idaluno}": {
      "patch": {
        "tags": [
          "Aluno"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "description": "Codigo do aluno",
            "value": 1
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Nenhum Conteúdo"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/professor": {
      "get": {
        "tags": [
          "Professor"
        ],
        "summary": "Consulta lista de professores.",
        "description": "Descrição do metodo",
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "post": {
        "tags": [
          "Professor"
        ],
        "description": "",
        "parameters": [
          {
            "name": "json",
            "description": "Dados para inserir um novo aluno",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "matricula": {
                  "type": "string",
                  "example": "12345678"
                },
                "cargo": {
                  "type": "string",
                  "example": "Professor"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Criado"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/professor/{idprofessor}": {
      "delete": {
        "tags": [
          "Professor"
        ],
        "description": "",
        "parameters": [
          {
            "name": "idprofessor",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Nenhum Conteúdo"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "professor/{idprofessor}": {
      "patch": {
        "tags": [
          "Professor"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "description": "Codigo do professor",
            "value": 1
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Nenhum Conteúdo"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/turma": {
      "get": {
        "tags": [
          "Turma"
        ],
        "summary": "Consulta lista de turmas.",
        "description": "Descrição do metodo",
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/genero": {
      "get": {
        "tags": [
          "Genero"
        ],
        "summary": "Consulta lista de generos.",
        "description": "Descrição do metodo",
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/autor": {
      "get": {
        "tags": [
          "Autor"
        ],
        "summary": "Consulta lista de autores.",
        "description": "Descrição do metodo",
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/editora": {
      "get": {
        "tags": [
          "Editora"
        ],
        "summary": "Consulta lista de editoras.",
        "description": "Rota para consultar a lista de todas as editoras cadastradas.",
        "responses": {
          "200": {
            "description": "Lista de editoras obtida com sucesso",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "number",
                    "example": 1
                  },
                  "nomeEditora": {
                    "type": "string",
                    "example": "Editora Exemplo"
                  },
                  "endereco": {
                    "type": "string",
                    "example": "Rua Exemplo, 123"
                  }
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "500": {
            "description": "Erro no servidor"
          }
        }
      },
      "post": {
        "tags": [
          "Editora"
        ],
        "summary": "Insere uma nova editora.",
        "description": "Rota para inserir uma nova editora no sistema.",
        "parameters": [
          {
            "name": "json",
            "description": "Dados para inserir uma nova editora",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "nomeEditora": {
                  "type": "string",
                  "example": "Editora Exemplo"
                },
                "endereco": {
                  "type": "string",
                  "example": "Rua Exemplo, 123"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Editora criada com sucesso",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "number",
                  "example": 1
                },
                "nomeEditora": {
                  "type": "string",
                  "example": "Editora Exemplo"
                },
                "endereco": {
                  "type": "string",
                  "example": "Rua Exemplo, 123"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "409": {
            "description": "Conflito"
          },
          "500": {
            "description": "Erro no servidor"
          }
        }
      }
    },
    "/editora/{ideditora}": {
      "delete": {
        "tags": [
          "Editora"
        ],
        "summary": "Remove uma editora.",
        "description": "Rota para remover uma editora do sistema pelo ID.",
        "parameters": [
          {
            "name": "ideditora",
            "in": "path",
            "required": true,
            "type": "integer",
            "description": "ID da editora",
            "example": 1
          }
        ],
        "responses": {
          "204": {
            "description": "Nenhum conteúdo (Editora removida com sucesso)"
          },
          "404": {
            "description": "Editora não encontrada"
          },
          "500": {
            "description": "Erro no servidor"
          }
        }
      },
      "patch": {
        "tags": [
          "Editora"
        ],
        "summary": "Atualiza parcialmente uma editora.",
        "description": "Rota para atualizar parcialmente uma editora pelo ID.",
        "parameters": [
          {
            "name": "ideditora",
            "in": "path",
            "required": true,
            "type": "integer",
            "description": "ID da editora",
            "example": 1
          },
          {
            "name": "json",
            "description": "Dados para atualizar a editora",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "nomeEditora": {
                  "type": "string",
                  "example": "Editora Exemplo"
                },
                "endereco": {
                  "type": "string",
                  "example": "Rua Exemplo, 123"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Editora atualizada com sucesso",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "number",
                  "example": 1
                },
                "nomeEditora": {
                  "type": "string",
                  "example": "Editora Exemplo"
                },
                "endereco": {
                  "type": "string",
                  "example": "Rua Exemplo, 123"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "404": {
            "description": "Editora não encontrada"
          },
          "409": {
            "description": "Conflito"
          },
          "500": {
            "description": "Erro no servidor"
          }
        }
      },
      "put": {
        "tags": [
          "Editora"
        ],
        "summary": "Atualiza todos os dados de uma editora.",
        "description": "Rota para atualizar todos os dados de uma editora pelo ID.",
        "parameters": [
          {
            "name": "ideditora",
            "in": "path",
            "required": true,
            "type": "integer",
            "description": "ID da editora",
            "example": 1
          },
          {
            "name": "json",
            "description": "Dados para substituir a editora",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "nomeEditora": {
                  "type": "string",
                  "example": "Editora Exemplo"
                },
                "endereco": {
                  "type": "string",
                  "example": "Rua Exemplo, 123"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Editora substituída com sucesso",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "number",
                  "example": 1
                },
                "nomeEditora": {
                  "type": "string",
                  "example": "Editora Exemplo"
                },
                "endereco": {
                  "type": "string",
                  "example": "Rua Exemplo, 123"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "404": {
            "description": "Editora não encontrada"
          },
          "409": {
            "description": "Conflito"
          },
          "500": {
            "description": "Erro no servidor"
          }
        }
      }
    }
  },
  "basepath": ""
}