{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "API TFLPIII HORUS BIBLIOTECA",
    "description": "Documentação da API TFLPIII HORUS BIBLIOTECA"
  },
  "host": "localhost:3000",
  "basePath": "/",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/usuario": {
      "get": {
        "tags": [
          "Usuario"
        ],
        "summary": "Consulta lista de usuarios.",
        "description": "Descrição do metodo",
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/aluno": {
      "get": {
        "tags": [
          "Aluno"
        ],
        "summary": "Consulta lista de alunos.",
        "description": "Descrição do metodo",
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "post": {
        "tags": [
          "Aluno"
        ],
        "description": "",
        "parameters": [
          {
            "name": "json",
            "description": "Dados para inserir um novo aluno",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "matricula": {
                  "type": "string",
                  "example": "12345678"
                },
                "dataNascimento": {
                  "type": "string",
                  "example": "2002-07-02"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Criado"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/aluno/{idaluno}": {
      "delete": {
        "tags": [
          "Aluno"
        ],
        "description": "",
        "parameters": [
          {
            "name": "idaluno",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Nenhum Conteúdo"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "aluno/{idaluno}": {
      "patch": {
        "tags": [
          "Aluno"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "description": "Codigo do aluno",
            "value": 1
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Nenhum Conteúdo"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/professor": {
      "get": {
        "tags": [
          "Professor"
        ],
        "summary": "Consulta lista de professores.",
        "description": "Descrição do metodo",
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "post": {
        "tags": [
          "Professor"
        ],
        "description": "",
        "parameters": [
          {
            "name": "json",
            "description": "Dados para inserir um novo aluno",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "matricula": {
                  "type": "string",
                  "example": "12345678"
                },
                "cargo": {
                  "type": "string",
                  "example": "Professor"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Criado"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/professor/{idprofessor}": {
      "delete": {
        "tags": [
          "Professor"
        ],
        "description": "",
        "parameters": [
          {
            "name": "idprofessor",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Nenhum Conteúdo"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "professor/{idprofessor}": {
      "patch": {
        "tags": [
          "Professor"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "description": "Codigo do professor",
            "value": 1
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Nenhum Conteúdo"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    }
  },
  "basepath": ""
}